"""add client_id to refresh_tokens

Revision ID: 3c41a92a7aab
Revises: 9d056ba9f866
Create Date: 2026-03-12 02:48:13.592893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c41a92a7aab'
down_revision: Union[str, None] = '9d056ba9f866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('client_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_client_id'), 'refresh_tokens', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_client_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'client_id')
    # ### end Alembic commands ###
