"""add family_id and is_used to refresh_tokens

Revision ID: 9d056ba9f866
Revises: a8eb1437df3a
Create Date: 2026-03-12 01:59:55.439002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d056ba9f866'
down_revision: Union[str, None] = 'a8eb1437df3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('family_id', sa.UUID(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('is_used', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'is_used')
    op.drop_column('refresh_tokens', 'family_id')
    # ### end Alembic commands ###
